### ISSUE TITLE
bug: Search button style broken on iPhone

### ISSUE THREAD

**Issue by itsValyria** [itsValyria/choices-choices-the-tech-stack#26]
### Search button styling doesn't work as intended
While testing my phone on multiple devices, I figured out the search button behaves in a way it shouldn't on my iPhone. I wasn't experiencing this issue in my Chrome developer mode, because I had the screen on a too big setting for the problem to show up.

<img src="https://github.com/user-attachments/assets/c3c48a5d-9c11-43bb-8269-5eb63b2e8733" alt="description of the image" width="300">

### How did I fix it?
Apparently I put a width on it, what caused it to break, because its a flexible element.

**Before**
```css
button {
  width: 15%; // This line is causing the issue.
  border: none;
  border-start-end-radius: var(--border-radius-md);
  border-end-end-radius: var(--border-radius-md);
  background-color: var(--button-background);
}
``` 

**After**
```css
button {
  border: none;
  border-start-end-radius: var(--border-radius-md);
  border-end-end-radius: var(--border-radius-md);
  background-color: var(--button-background);
}
```

### Does it work now?
The answer is yes.

<img src="https://github.com/user-attachments/assets/495fa97e-06fa-4233-af2d-1a2be64acc39" alt="description of the image" width="300">
