### ISSUE TITLE
Code conventions

### ISSUE THREAD

**Issue by itsValyria** [itsValyria/choices-choices-the-tech-stack#5]
### My code conventions for this project

- Everything in EN
- 2 space tab indents
- BEM class naming
- Custom properties in global.css
- Work with components, stored in lib folder
- Building the site mobile-first
- No CSS nesting due to bad media query support
- Use camelCasing in JS
- Write comments for complex code
- Use ''fix'' or ''fixes'' in commit messages to keep them clean and automatically close issues when solved

**Comment by itsValyria** [comment]
## Examples

### BEM naming
```css
.webinar__carousel {
      display: flex;
      overflow-x: auto;
      scroll-snap-type: x mandatory;
      scroll-padding-left: 0px;
      -webkit-overflow-scrolling: touch;
      scroll-behavior: smooth;
      margin: 0 auto;
      gap: 10px;
  }

  .webinar__carousel li a {
    display: flex;
    align-items: flex-start;
    flex-direction: column;
    padding: 0;
  }

  .webinar__image--container {
    position: relative;
  }

  .webinar__image--container img {
    height: 12em;
    border-radius: var(--border-radius-sm);
  }
```

### Custom properties

```css
:root {
  /* Fonts */
  --primary-font: "Open Sans", sans-serif;
  --heading-font: "VAGRundschrift", sans-serif;

  /* Font sizes */
  --font-size-xs: 0.75rem;
  --font-size-sm: 0.875rem;
  --font-size-md: 1rem;
  --font-size-lg: 1.25rem;
  --font-size-xl: 1.5rem;
  --font-size-2xl: 2rem;
  --font-size-3xl: 3rem;

  /* Colors: generic */
  --darker-black: #000;
  --lighter-black: #222222;

  --darker-white: #F0E5E9;
  --lighter-white: #fff;

  --darker-red: #6a0025;
  --lighter-red: #D2B2BD;

  /* Colors: element */
  --primary-color: var(--darker-red);
  --secondary-color: var(--lighter-red);

  --body-background-color: var(--darker-white);
  
  --focus: solid 2px var(--darker-red);
  
  --navigation-active: var(--darker-red);

  --button-background: var(--darker-red);
  --button-text: var(--lighter-white);

  --text-accent: var(--darker-red);

  /* Border radius */
  --border-radius-xs: 4px;
  --border-radius-sm: 6px;
  --border-radius-md: 12px;
  --border-radius-lg: 18px;
  --border-radius-xl: 24px
}
```

### Use fix or fixes in commit messages

![image](https://github.com/user-attachments/assets/9acf4b5e-e1c1-4f12-9663-4cf135c59a90)
