### ISSUE TITLE
Build scrolling list for the preview cards

### ISSUE THREAD

**Issue by itsValyria** [itsValyria/choices-choices-the-tech-stack#9]
### Carousel

By using ```display: flex``` and ```overflow-x: auto;``` I created a simple yet effective carousel.

### HTML

```html
<ul class="webinar__carousel">
  {webinars.slice(0, 4).map(webinar => (
    <li>
      <article>
        <a href={`/webinars/${webinar.slug}`}>
          <div class="webinar__image--container">
            <img src={`https://fdnd-agency.directus.app/assets/${webinar.thumbnail.id}`} alt="thumbnail" />
            <p class="webinar__duration">{webinar.duration}</p>
          </div>
          <h3>{webinar.title}</h3>
          <p class="webinar__speakers">
            {webinar.speakers.map(speaker => (
              <span>{speaker.avl_speakers_id.fullname}</span>
            ))}
          </p>
          <div class="webinar__categories">
            {webinar.categories.map(category => (
              <p class="webinar__category">{category.avl_categories_id.name}</p>
            ))}
          </div>
        </a>
      </article>
    </li>
  ))}
</ul>
```

### CSS

```css
.webinar__carousel {
    display: flex;
    overflow-x: auto;
    scroll-snap-type: x mandatory;
    scroll-padding-left: 0px;
    -webkit-overflow-scrolling: touch;
    scroll-behavior: smooth;
    margin: 0 auto;
    gap: 10px;
}
```
